name: Create Resourcepack ZIP

on:
  push:
    branches:
      - main
    paths:
      - 'resourcepack/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create resourcepack ZIP file
        run: zip -r resourcepack.zip resourcepack

      - name: Commit and push ZIP file
        run: |
          git config --global user.name 'lineside0418'
          git config --global user.email 'maincraft0418yuta@gmail.com'
          git add resourcepack.zip
          git commit -m "feat: Update resourcepack.zip"
          git push
